import SearchHeader from '@/components/SearchHeader'
import './../globals.css'


export const metadata = {
    title: 'Google Clone Next Js 13',
    description: 'Generated by create next app',
}

export default function SeachLayout({ children }) {
    return (
        <div>
            <SearchHeader />
            {children}
        </div>
    )
}
